# Generated by Django 3.2.3 on 2021-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('dou', models.CharField(max_length=50, unique=True, verbose_name='DOU - Identificação')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('data_abertura', models.DateTimeField(null=True, verbose_name='Data de abertura')),
                ('orgao', models.CharField(max_length=100, null=True, verbose_name='Orgão')),
                ('resumo', models.TextField()),
                ('modalidade', models.IntegerField(choices=[(0, 'Concorrência'), (1, 'Convite / Carta-convite'), (2, 'Tomada de Preços'), (3, 'Leilão'), (4, 'Concurso'), (5, 'Pregão')], verbose_name='Modalidade')),
                ('edital', models.FileField(upload_to='media/documents')),
            ],
            options={
                'verbose_name': 'Licitações',
            },
        ),
    ]
