# Generated by Django 3.2.3 on 2021-05-22 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='DataCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('registration_status', models.CharField(max_length=50, verbose_name='Situação Cadastral')),
                ('registration_date', models.DateField(verbose_name='Data do Registro')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('city', models.CharField(max_length=100, verbose_name='Municipio')),
                ('street', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('zip', models.CharField(max_length=10, verbose_name='CEP')),
                ('legal_nature_code', models.CharField(max_length=10, verbose_name='Natureza Legal - ID')),
                ('legal_nature_description', models.CharField(max_length=100, verbose_name='Natureza Legal - Descrição')),
                ('primary_activity_code', models.CharField(max_length=10, verbose_name='Atividade Primária - CNAE')),
                ('primary_activity_description', models.CharField(max_length=100, verbose_name='Atividade Primária - Descrição')),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_cnpj', to='clients.company')),
            ],
            options={
                'verbose_name': 'Dados da Empresa',
            },
        ),
        migrations.CreateModel(
            name='SecondaryActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='CNAE')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('data_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_activities', to='clients.datacompany')),
            ],
            options={
                'verbose_name': 'Atividades Secundárias',
            },
        ),
    ]
